enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"backbone",
	"model.js",
	"collection.js",
	"style/App.css",
    "resources/translation.js",
	"App.js",
	"Expense.js",
	"ExpensesList.js",
	"Lista.js",
	"SubRepView.js",
	"PageOne.js",
	"PageTwo.js",
	"PageThree.js",
	"WizardManager.js"
);
